First pass at computed-properties-transform
This is unfortunately broken. The built-in esprima parser doesn't know
how to handle decorators, and switching to the babel parser seems to not
work due to it failing with ES6 exports (?):

  AssertionError: did not recognize object of type
  "ExportDefaultDeclaration"